allowBuilds:
  '@firebase/util': true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  postcss: ">=8.5.10"
  "@grpc/grpc-js": ">=1.9.16"

patchedDependencies:
  postcss: patches/postcss.patch
